//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int payment_id { get; set; }
        public int project_id { get; set; }
        public int user_id { get; set; }
        public decimal amount { get; set; }
        public string rewards { get; set; }
        public System.DateTime payment_date { get; set; }
        public string payment_method { get; set; }
        public Nullable<System.DateTime> refunded_amount { get; set; }
        public string refunded_date { get; set; }
    
        public virtual project project { get; set; }
        public virtual user user { get; set; }
    }
}
