//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project()
        {
            this.payment = new HashSet<payment>();
            this.project_funding_level = new HashSet<project_funding_level>();
            this.project_photo = new HashSet<project_photo>();
        }
    
        public int project_id { get; set; }
        public int user_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string short_description { get; set; }
        public decimal goal { get; set; }
        public Nullable<decimal> goal_min { get; set; }
        public Nullable<int> photo_id_main { get; set; }
        public string video { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public bool is_active { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<System.DateTime> deleted_date { get; set; }
        public Nullable<System.DateTime> blocked_date { get; set; }
        public Nullable<int> state_id { get; set; }
        public string website { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment> payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_funding_level> project_funding_level { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_photo> project_photo { get; set; }
        public virtual project_category project_category { get; set; }
        public virtual project_photo project_photo1 { get; set; }
        public virtual project_state project_state { get; set; }
        public virtual user user { get; set; }
    }
}
