//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.payment = new HashSet<payment>();
            this.project = new HashSet<project>();
            this.user_address = new HashSet<user_address>();
            this.user_photo = new HashSet<user_photo>();
        }
    
        public int user_id { get; set; }
        public string password { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string username { get; set; }
        public string email_primary { get; set; }
        public string email_secondary { get; set; }
        public string telephone { get; set; }
        public string mobile { get; set; }
        public string about { get; set; }
        public Nullable<int> photo_main_id { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public int points { get; set; }
        public bool is_active { get; set; }
        public System.DateTime registration_date { get; set; }
        public Nullable<System.DateTime> deletion_date { get; set; }
        public Nullable<System.DateTime> blocked_date { get; set; }
        public bool is_admin { get; set; }
        public Nullable<int> address_id_main { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment> payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project> project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_address> user_address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_photo> user_photo { get; set; }
        public virtual user_address user_address1 { get; set; }
        public virtual user_photo user_photo1 { get; set; }
    }
}
